server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlexyuS/config-app-1
          search-paths:
          - 'config-app-1/team*'
          - 'config-app-1'         
           
                            
            
